### ISSUE TITLE
Add govulncheck to CI

### ISSUE THREAD

**Issue by case-fastly** [zonedb/zonedb#971]
https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck

**Comment by cee-dub** [comment]
Add to any workflow:

https://github.com/marketplace/actions/golang-govulncheck-action

```yml
- id: govulncheck
  uses: golang/govulncheck-action@v1
  with:
    go-version-file: go.mod
```
